import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class SnakeBoard extends JFrame {
    private JPanel mainPanel;
    private JButton startANewGameButton;
    private JLabel snakeInitialLabel;
    private JTextPane snakeBoardInitialScreenTextPane;

    public SnakeBoard() {
        startANewGameButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // TODO When the board is created: start the game
                JOptionPane.showMessageDialog(startANewGameButton, snakeBoardInitialScreenTextPane.getText() + "Dupa");
            }
        });

//        setContentPane(mainPanel);
        setTitle("Ssssssssssnake");
        setSize(720, 720);
//        setVisible(true);
        setResizable(false);

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

//        addKeyListener(game);
//        thread.start();
    }

    public static void main(String[] args) {

        SnakeBoard board = new SnakeBoard();
        GameThread dupa = new GameThread();
        board.add(dupa);
        EventQueue.invokeLater(() -> board.setVisible(true));

        try {
            Thread.sleep(500);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Thread thread = new Thread(dupa);
        thread.start();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        startANewGameButton = new JButton();
        startANewGameButton.setText("Start a new game for two players");
        mainPanel.add(startANewGameButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        snakeInitialLabel = new JLabel();
        snakeInitialLabel.setText("Hello in snake! :D");
        mainPanel.add(snakeInitialLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        snakeBoardInitialScreenTextPane = new JTextPane();
        snakeBoardInitialScreenTextPane.setText("SnakeBoard: Initial screen");
        mainPanel.add(snakeBoardInitialScreenTextPane, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}


